# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "marimo",
#     "jax",
#     "jaxlib", 
#     "numpy",
#     "matplotlib",
#     "schrodinger-bridge",
# ]
# ///

import marimo

__generated_with = "0.14.10"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    import jax
    import jax.numpy as jnp
    import numpy as np
    import matplotlib.pyplot as plt

    key = jax.random.PRNGKey(42)
    return (mo,)


@app.cell
def _(mo):
    mo.md(
        r"""
    # Koopman-Accelerated Schrödinger Bridge Solvers

    **Faster Training via Operator Theory & Sparse Dynamics**

    This guide covers the Koopman-based acceleration methods for SB solvers:

    1. **The Deep Connection** — Fokker-Planck, Kolmogorov Backward, and Koopman operators
    2. **When Eigenfunction Expansions Hold** — Critical assumptions and limitations
    3. **Discrete vs Continuous Time** — When to use EDMD vs gEDMD
    4. **EDMD Warm-Start** — Fast initialization via eigenfunctions
    5. **gEDMD Solver** — Direct drift via generator approximation  
    6. **HyperSINDy Solver** — Sparse, interpretable drift learning
    7. **Discrete-Time IPF-Koopman** — For daily/low-frequency data
    8. **When Koopman Methods Excel** — Practical decision guide

    ---
    """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## 1. The Deep Connection: Three Fundamental PDEs/Operators

    For an SDE $dX_t = b(X_t)dt + \sigma dW_t$, there are three intimately related mathematical objects:

    ### 1.1 The Fokker-Planck Equation (Forward Kolmogorov)

    Describes how **probability densities evolve forward** in time:

    $$\boxed{\frac{\partial p}{\partial t} = -\nabla \cdot (b \, p) + \frac{\sigma^2}{2} \Delta p = \mathcal{L}^* p}$$

    where $\mathcal{L}^*$ is the **Fokker-Planck operator** (adjoint of the generator).

    - **Input**: Initial density $p(x, 0) = p_0(x)$
    - **Output**: Density at time $t$: $p(x, t)$
    - **Interpretation**: "Where does the probability mass flow?"

    ### 1.2 The Kolmogorov Backward Equation

    Describes how **expected values evolve backward** in time:

    $$\boxed{\frac{\partial u}{\partial t} + b \cdot \nabla u + \frac{\sigma^2}{2} \Delta u = \frac{\partial u}{\partial t} + \mathcal{L} u = 0}$$

    where $\mathcal{L}$ is the **infinitesimal generator**.

    - **Input**: Terminal condition $u(x, T) = g(x)$ (some payoff/observable)
    - **Output**: $u(x, t) = \mathbb{E}[g(X_T) | X_t = x]$
    - **Interpretation**: "What's the expected future value from here?"

    ### 1.3 The Koopman Operator

    The **semigroup** generated by $\mathcal{L}$:

    $$\boxed{(\mathcal{K}_t g)(x) = \mathbb{E}[g(X_t) | X_0 = x] = e^{t\mathcal{L}} g}$$

    - **Action**: Evolves observables forward along trajectories
    - **Key property**: Linear (even for nonlinear dynamics!) but infinite-dimensional
    - **Eigenfunctions**: $\mathcal{L}\phi_j = \lambda_j \phi_j \Rightarrow \mathcal{K}_t \phi_j = e^{\lambda_j t} \phi_j$

    ### 1.4 The Duality

    Fokker-Planck and Kolmogorov Backward are **adjoint** to each other:

    $$\int p(x,t) \, u(x,t) \, dx = \text{constant in } t$$

    This means:
    - **Fokker-Planck** pushes densities forward: $p_t = e^{t\mathcal{L}^*} p_0$
    - **Koopman/Backward** pulls functions backward: $u_t = e^{(T-t)\mathcal{L}} g$

    They contain the **same information** viewed from different perspectives!
    """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ### 1.5 Connection to Schrödinger Bridge

    The SB potential $\psi(x,t)$ satisfies the **Backward Kolmogorov equation**:

    $$\frac{\partial \psi}{\partial t} + \mathcal{L}_{\text{ref}} \psi = 0, \quad \psi(x, T) = \psi_T(x)$$

    where $\psi_T$ is determined by the target marginal $\mu_1$.

    Similarly, the conjugate potential $\hat{\psi}(x,t)$ satisfies **Fokker-Planck**:

    $$\frac{\partial \hat{\psi}}{\partial t} = \mathcal{L}^*_{\text{ref}} \hat{\psi}, \quad \hat{\psi}(x, 0) = \hat{\psi}_0(x)$$

    The optimal SB drift is:

    $$b^*(x,t) = b_{\text{ref}}(x,t) + \sigma^2 \nabla \log \psi(x,t)$$

    **This is why Koopman theory is relevant**: $\psi$ solves the backward equation, 
    so it can be expressed in terms of **generator eigenfunctions**!
    """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## 2. When Does the Eigenfunction Expansion Hold?

    We claimed that the SB potential can be written as:

    $$\psi(x,t) = \sum_j c_j e^{\lambda_j (T-t)} \phi_j(x)$$

    **This is a powerful formula, but it requires several conditions to hold!**

    ### 2.1 Required Conditions

    | Condition | What It Means | When It Fails |
    |-----------|---------------|---------------|
    | **Discrete spectrum** | $\mathcal{L}$ has countable eigenvalues | Continuous spectrum (unbounded domains, some potentials) |
    | **Complete eigenfunctions** | $\{\phi_j\}$ spans the relevant function space | Non-self-adjoint operators, deficient spectrum |
    | **Convergent expansion** | Series converges for $\psi_T$ | $\psi_T$ not in domain, rough terminal condition |
    | **Real/stable eigenvalues** | $\text{Re}(\lambda_j) \leq 0$ for stability | Unstable dynamics (eigenvalues with positive real part) |

    ### 2.2 When It Works Well

    ✅ **Ornstein-Uhlenbeck process**: $dX = -\theta X \, dt + \sigma dW$

    - Generator: $\mathcal{L} = -\theta x \cdot \nabla + \frac{\sigma^2}{2}\Delta$
    - Eigenfunctions: **Hermite polynomials** $H_n(x)$
    - Eigenvalues: $\lambda_n = -n\theta$ (discrete, negative)
    - Expansion converges for any $\psi_T \in L^2(\text{Gaussian})$

    ✅ **Bounded domain with reflecting/absorbing boundaries**

    - Discrete spectrum guaranteed by compactness
    - Eigenfunctions form complete orthonormal basis

    ✅ **Gradient systems**: $b(x) = -\nabla V(x)$ with confining potential

    - Self-adjoint generator (w.r.t. invariant measure)
    - Real eigenvalues, complete eigenfunctions

    ### 2.3 When It Breaks Down

    ❌ **Pure Brownian motion on $\mathbb{R}^d$**: $dX = \sigma dW$

    - Generator: $\mathcal{L} = \frac{\sigma^2}{2}\Delta$
    - **Continuous spectrum** $(-\infty, 0]$, no discrete eigenfunctions!
    - Eigenfunctions are $e^{ik \cdot x}$ (Fourier modes), not $L^2$

    ❌ **Non-normal operators** (highly non-self-adjoint)

    - Eigenfunctions may not span the space
    - Pseudospectral effects: small perturbations → large changes

    ❌ **Rough terminal conditions**

    - If $\psi_T$ is discontinuous or has sharp features
    - Eigenfunction series converges slowly or not at all

    ### 2.4 The Practical Implication

    For **Brownian motion reference** (the most common case!), the eigenfunction expansion 
    doesn't strictly hold. So why does EDMD still help?

    **Answer**: EDMD gives a **finite-rank approximation** that captures the dominant 
    dynamics in your dictionary subspace. It's not computing "true" eigenfunctions 
    (which don't exist in $L^2$), but rather the best projection onto your chosen basis.

    This works because:

    1. Your source/target have **compact support** (practically)
    2. The dictionary spans the relevant functions on that support
    3. The approximation is good enough for warm-starting, even if not exact
    """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## 3. Discrete-Time vs Continuous-Time: A Critical Choice

    ### 3.1 The Fundamental Tradeoff

    | Aspect | Continuous-Time (gEDMD) | Discrete-Time (EDMD) |
    |--------|------------------------|---------------------|
    | **Approximates** | Generator $\mathcal{L}$ | Koopman operator $\mathcal{K}_{\Delta t}$ |
    | **Requires** | Time derivatives $\dot{X}$ | Snapshot pairs $(X_k, X_{k+1})$ |
    | **Noise sensitivity** | High (differencing amplifies noise) | Moderate |
    | **Best for** | High-frequency data, simulations | Daily data, noisy observations |

    ### 3.2 The Derivative Estimation Problem

    gEDMD needs $\dot{X} = dX/dt$. From discrete data:

    $$\dot{X}_k \approx \frac{X_{k+1} - X_k}{\Delta t}$$

    **Noise amplification**: If $X_k = X^{\text{true}}_k + \epsilon_k$ with noise $\epsilon \sim \mathcal{N}(0, \sigma^2)$:

    $$\text{Var}(\dot{X}_k) \approx \frac{2\sigma^2}{(\Delta t)^2}$$

    For daily financial data ($\Delta t = 1/252 \approx 0.004$):

    - Noise in derivative is amplified by factor $\sim 250^2 = 62,500$!
    - This destroys the generator estimate

    ### 3.3 When to Use Which

    **Use gEDMD (continuous-time) when:**

    - $\Delta t < 0.01$ (high-frequency: tick data, simulations)
    - Data is clean (simulated trajectories)
    - You need the generator explicitly (PDE solvers)

    **Use EDMD (discrete-time) when:**

    - $\Delta t \geq 0.01$ (daily, weekly data)
    - Data is noisy (real-world observations)
    - You can work with $\mathcal{K}_{\Delta t}$ directly

    ### 3.4 Converting Between Them (With Caution!)

    In principle: $\mathcal{L} = \frac{1}{\Delta t} \log \mathcal{K}_{\Delta t}$

    **This is numerically dangerous because:**

    1. Matrix logarithm requires eigenvalues in safe region
    2. Small eigenvalues of $K$ → large negative eigenvalues of $L$
    3. Numerical errors get amplified

    **If you must convert**, use rank truncation:

    ```python
    # Only keep eigenvalues safely away from 0
    K_truncated = U[:, :r] @ jnp.diag(S[:r]) @ Vh[:r, :]
    L_approx = jnp.real(jax.scipy.linalg.logm(K_truncated)) / dt
    ```
    """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## 4. EDMD Warm-Start Solver

    ### 4.1 The Strategy

    1. Generate reference SDE trajectories (from source distribution)
    2. Apply EDMD to approximate Koopman operator $\tilde{K}_{\Delta t}$
    3. Extract approximate eigenfunctions from eigenvectors
    4. Construct warm-start drift from leading eigenmodes
    5. Distill into neural network (fast, since target is smooth)
    6. Fine-tune with standard score matching

    **Key point**: We apply EDMD to the **entire trajectory dataset** (not windows) 
    because we need eigenfunctions valid over the full state space.

    ### 4.2 Usage

    ```python
    from schrodinger_bridge.solvers.koopman import EDMDWarmStartSolver, EDMDWarmStartConfig

    config = EDMDWarmStartConfig(
        dictionary_type='hermite',      # Natural for OU-like dynamics
        hermite_order=4,                # Max polynomial order
        num_koopman_modes=15,           # Leading eigenfunctions
        warmstart_iterations=1000,      # Distillation steps
        refinement_iterations=3000,     # vs ~10000 from scratch
    )

    solver = EDMDWarmStartSolver(problem, config)
    result = solver.train(key)
    ```

    ### 4.3 Why Hermite Polynomials?

    For OU process $dX = -\theta X \, dt + \sigma dW$:
    - Invariant measure: $\pi(x) \propto e^{-\theta x^2/\sigma^2}$ (Gaussian)
    - Generator eigenfunctions: Hermite polynomials $H_n(x)$
    - They're orthogonal w.r.t. the Gaussian measure

    Even for non-OU references, Hermite polynomials work well when:
    - The process has a Gaussian-like invariant measure
    - Source/target are approximately Gaussian
    - You're in the "diffusion-dominated" regime
    """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## 5. gEDMD Solver: Direct Generator Approximation

    ### 5.1 When to Use gEDMD

    **Appropriate for:**

    - High-frequency data ($\Delta t < 0.01$)
    - Clean simulation data
    - When you need the generator explicitly

    **NOT appropriate for:**

    - Daily financial data ($\Delta t = 1/252$)
    - Noisy real-world observations
    - When discrete-time IPF would suffice

    ### 5.2 The Algorithm

    Given state $X$ and time derivative $\dot{X} = dX/dt$:

    1. Evaluate dictionary $\Psi(X)$ and its derivatives $\nabla \Psi(X)$, $\Delta \Psi(X)$
    2. Compute $\frac{d\Psi}{dt} = \nabla \Psi \cdot \dot{X} + \frac{\sigma^2}{2} \Delta \Psi$ (Itô's lemma)
    3. Solve: $\frac{d\Psi}{dt} = L \Psi$ for generator matrix $L$

    ### 5.3 Direct Drift Identification

    The generator encodes the drift directly! For coordinate function $\psi_i(x) = x_i$:

    $$\mathcal{L}x_i = b_i(x) + 0 = b_i(x)$$

    So the first $d$ rows of the generator matrix (after the constant) give drift coefficients.

    ### 5.4 Usage (For Appropriate Data!)

    ```python
    from schrodinger_bridge.solvers.koopman import GEDMDSolver, GEDMDConfig

    # Only use if you have high-frequency or simulation data!
    config = GEDMDConfig(
        dictionary_type='hermite',
        hermite_order=5,
        regularization=1e-6,
        time_derivative_method='central_difference',
    )

    solver = GEDMDSolver(problem, config)
    result = solver.train(key)  # One-shot computation
    ```
    """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## 6. HyperSINDy Solver: Sparse Stochastic Dynamics

    ### 6.1 The Core Idea

    Most dynamical systems have **sparse** governing equations in an appropriate basis:

    $$dX = \underbrace{\Theta(X,t)}_{\text{dictionary}} \underbrace{\xi}_{\text{sparse}} dt + \sigma dW$$

    HyperSINDy discovers this sparse structure automatically.

    ### 6.2 Why Sparsity Matters for SB

    The SB drift correction often has sparse structure because:

    1. **Physical parsimony**: Nature prefers simple equations
    2. **Polynomial structure**: For Gaussian marginals, optimal drift is linear
    3. **Interpretability**: Sparse equations reveal essential dynamics

    **Example**: Gaussian-to-Gaussian SB has *exactly* linear drift:
    $$b^*(x,t) = A(t)x + c(t)$$

    HyperSINDy would discover this with only $d+1$ active terms!

    ### 6.3 The Hard Concrete Distribution

    Sparsity via differentiable relaxation of Bernoulli:

    $$z = \text{clamp}\left[\sigma\left(\frac{\log u - \log(1-u) + \log\alpha}{\beta}\right)(\zeta - \gamma) + \gamma, 0, 1\right]$$

    - $\log \alpha$: learnable inclusion probability
    - $\beta$: temperature (lower = sparser)
    - Allows gradient-based learning of which terms matter

    ### 6.4 Usage

    ```python
    from schrodinger_bridge.solvers.koopman import HyperSINDySolver, HyperSINDySolverConfig

    config = HyperSINDySolverConfig(
        polynomial_degree=3,
        latent_dim=32,
        sparsity_lambda=0.1,      # Higher = sparser
        sparsity_temperature=0.5,
    )

    solver = HyperSINDySolver(problem, config)
    result = solver.train(key)

    # Extract discovered equation
    equation = get_sparse_equation(solver._hypersindy_params, solver._dictionary, dim=2)
    print(f"Found {equation['num_active']} active terms")
    ```
    """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## 7. Discrete-Time IPF-Koopman Solver

    ### 7.1 Why Discrete-Time?

    For **daily financial data** or other low-frequency observations, 
    the discrete-time formulation is more appropriate:

    - No noisy derivative estimation
    - Directly models $X_{k+1} | X_k$
    - Naturally handles the actual observation frequency

    ### 7.2 The Discrete-Time SB Problem

    Instead of continuous SDEs, consider the Markov chain:

    $$X_{k+1} \sim P_{\text{ref}}(\cdot | X_k)$$

    The discrete SB finds the minimum-entropy modification:

    $$P^* = \arg\min_{P: P_0 = \mu_0, P_N = \mu_1} \text{KL}(P \| P_{\text{ref}})$$

    This is solved by **Iterative Proportional Fitting (IPF)** / Sinkhorn!

    ### 7.3 Koopman-Enhanced IPF

    EDMD gives us $\tilde{K}_{\Delta t} \approx \mathcal{K}_{\Delta t}$ in dictionary space.

    **Key insight**: The Koopman operator encodes transition probabilities:

    $$(\mathcal{K}_{\Delta t} g)(x) = \int g(y) P_{\text{ref}}(dy | x)$$

    So EDMD's $\tilde{K}$ gives us the reference transition structure!

    ### 7.4 The Algorithm

    1. Fit EDMD to historical data: $\Psi(X_{k+1}) \approx \tilde{K} \Psi(X_k)$
    2. Use $\tilde{K}$ to define reference transitions in feature space
    3. Run IPF/Sinkhorn between:
       - Source: $\mu_0$ projected to dictionary space
       - Target: $\mu_1$ projected to dictionary space
       - Reference: Transitions induced by $\tilde{K}$
    4. Map optimal coupling back to state space

    ### 7.5 Advantages for Finance

    - **No derivative estimation**: Works with daily/weekly data
    - **Noise robust**: EDMD + regularization handles market noise
    - **Discrete nature matches reality**: Markets are observed discretely
    - **IPF is well-understood**: Convergence guarantees, efficient algorithms

    ### 7.6 Usage

    ```python
    from schrodinger_bridge.solvers.koopman import DiscreteIPFKoopmanSolver, DiscreteIPFConfig

    config = DiscreteIPFConfig(
        dictionary_type='polynomial',
        polynomial_degree=3,
        num_sinkhorn_iterations=100,
        regularization=1e-4,  # Higher for noisy data
        use_optdmd=True,      # Noise-robust fitting
    )

    solver = DiscreteIPFKoopmanSolver(problem, config)
    result = solver.train(key)
    ```
    """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## 8. When Koopman Methods Excel

    ### 8.1 The Ideal Conditions

    Koopman-accelerated solvers work best when:

    | Condition | Why It Helps |
    |-----------|--------------|
    | **Known reference dynamics** | Can generate clean trajectories for EDMD |
    | **Polynomial/sparse drift structure** | Dictionary captures it efficiently |
    | **Moderate dimension ($d \leq 10$)** | Dictionary size manageable |
    | **Smooth, unimodal marginals** | Eigenfunction expansion converges |
    | **Need for interpretability** | HyperSINDy gives explicit equations |

    ### 8.2 The Challenging Conditions

    | Condition | Why Koopman Struggles |
    |-----------|----------------------|
    | **Pure Brownian reference** | No discrete spectrum (but finite-rank approx still helps!) |
    | **Highly multimodal targets** | Need many eigenfunctions |
    | **High dimension ($d > 20$)** | Dictionary explodes combinatorially |
    | **Daily/low-frequency data** | Use discrete-time IPF, not gEDMD |
    | **Heavy noise** | Use optDMD/Bagging, not standard EDMD |

    ### 8.3 Decision Flowchart

    ```
    What is your data frequency?
    │
    ├── High-frequency (dt < 0.01) or simulation
    │   └── Is the reference dynamics known analytically?
    │       ├── YES → gEDMD or EDMD Warm-Start
    │       └── NO → Empirical reference + EDMD
    │
    └── Low-frequency (daily, weekly)
        └── Use Discrete-Time IPF-Koopman
            └── Is data noisy?
                ├── YES → optDMD / Bagging-optDMD
                └── NO → Standard EDMD

    Do you need interpretable equations?
    ├── YES → HyperSINDy (works with either formulation)
    └── NO → Continue with EDMD/IPF approach
    ```

    ### 8.4 Quantitative Guidance

    | Method | Typical Speedup | Best Data Type | Noise Tolerance |
    |--------|-----------------|----------------|-----------------|
    | EDMD Warm-Start | 2-5× | Simulated, HF | Low-Moderate |
    | gEDMD | 10-50× | Simulated, HF | Low |
    | HyperSINDy | 5-20× | Any | Moderate |
    | Discrete IPF-Koopman | 2-10× | Daily, LF | High (with optDMD) |
    | optDMD variants | — | Noisy real data | High |
    """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## 9. Summary: The Mathematical Hierarchy

    ### The Three Levels

    ```
    Level 1: PDEs (Continuous)
    ┌─────────────────────────────────────────────────────────┐
    │  Fokker-Planck: ∂p/∂t = L*p    (densities forward)     │
    │  Kolmogorov Backward: ∂u/∂t + Lu = 0  (values backward)│
    │  SB Potential: ψ solves backward with terminal from μ₁ │
    └─────────────────────────────────────────────────────────┘
                              │
                              ▼
    Level 2: Operators (Infinite-Dimensional)
    ┌─────────────────────────────────────────────────────────┐
    │  Generator: L = b·∇ + (σ²/2)Δ                          │
    │  Koopman semigroup: K_t = exp(tL)                      │
    │  Eigenfunction expansion: ψ = Σ cⱼ exp(λⱼt) φⱼ         │
    │  ⚠️ Requires discrete spectrum + completeness!         │
    └─────────────────────────────────────────────────────────┘
                              │
                              ▼
    Level 3: Matrices (Finite-Dimensional Approximation)
    ┌─────────────────────────────────────────────────────────┐
    │  EDMD: K̃ approximates K_Δt in dictionary basis         │
    │  gEDMD: L̃ approximates L (needs small Δt!)            │
    │  optDMD: Noise-robust K̃ via optimization              │
    │  IPF: Discrete-time SB via Sinkhorn on K̃              │
    └─────────────────────────────────────────────────────────┘
    ```

    ### Key Takeaways

    1. **Fokker-Planck and Kolmogorov Backward are adjoint**: Same information, different viewpoints

    2. **Eigenfunction expansion requires conditions**: Discrete spectrum, completeness, convergence

    3. **Pure Brownian motion has continuous spectrum**: Eigenfunction expansion doesn't strictly hold, 
       but finite-rank EDMD approximation still provides useful warm-start

    4. **Discrete-time for low-frequency data**: Don't use gEDMD on daily data; use EDMD + IPF

    5. **optDMD for noisy data**: Standard EDMD is biased; use optimization-based variants

    6. **The SB drift correction** $\sigma^2 \nabla \log \psi$ can be approximated via 
       eigenfunction gradients when the expansion holds, or via dictionary regression otherwise

    ---

    **Happy bridging! 🌉**
    """
    )
    return


if __name__ == "__main__":
    app.run()
