"""Cross-fitted scalar value critic for MAM diagnostics and baselines.

The critic is deliberately trained on a frozen return cache.  A row assigned
to fold zero is *only* evaluated by the model trained on fold one, and vice
versa.  Consequently the stopped predictions are valid cross-fitted
control-variate candidates for that cache.  They do not make a Malliavin or
score label unbiased by themselves; the centering identity used by the caller
must still be valid for the estimator in question.

The spatial gradient of the same opposite-fold value model is exposed as the
``critic_autodiff`` costate comparison.  This is a mandatory empirical
baseline for MAM, not evidence that either estimator is accurate.  Endpoint
context is concatenated with state while time remains the NetworkFactory time
input.  Gradients are taken with respect to state only, holding endpoint and
time fixed.
"""

from __future__ import annotations

import hashlib
import math
from dataclasses import dataclass
from numbers import Integral, Real
from typing import Any, NamedTuple

import jax
import jax.numpy as jnp
import numpy as np

from ..core.types import Array, Params, PRNGKey
from ..network_factory import MLPFactory, NetworkFactory, sanity_check
from ..networks import AdamState, adam_update, init_adam

CRITIC_AUTODIFF_METHOD = 0


@dataclass(frozen=True)
class FixedPolicyReturnDataset:
    """A caller-certified fixed-policy return cache.

    Shapes:
        states: ``[B,d]``
        times: ``[B]``
        endpoint_context: ``[B,c]``
        returns: ``[B]``

    ``policy_fingerprint`` is provenance, not a mathematical check: callers
    must ensure every return was generated by the same frozen policy and cost
    convention.  Mixing policies invalidates the intended critic comparison.
    """

    states: Array
    times: Array
    endpoint_context: Array
    returns: Array
    policy_fingerprint: str


@dataclass(frozen=True)
class ValueCriticConfig:
    """Training configuration for two scalar value models."""

    hidden_dims: tuple[int, ...] = (128, 128)
    time_embed_dim: int = 32
    learning_rate: float = 1e-3
    training_steps: int = 1_000
    microbatch_size: int = 128
    effective_batch_size: int = 1_024
    weight_decay: float = 0.0
    network_factory: NetworkFactory | None = None

    def __post_init__(self) -> None:
        def require_integer(name: str, value: Any, *, minimum: int) -> None:
            if isinstance(value, (bool, np.bool_)) or not isinstance(value, Integral):
                raise TypeError(f"{name} must be an integer")
            if int(value) < minimum:
                raise ValueError(f"{name} must be at least {minimum}")

        def require_real(name: str, value: Any, *, minimum: float, strict: bool) -> None:
            if isinstance(value, (bool, np.bool_)) or not isinstance(value, Real):
                raise TypeError(f"{name} must be a real number")
            scalar = float(value)
            if not math.isfinite(scalar):
                raise ValueError(f"{name} must be finite")
            invalid = scalar <= minimum if strict else scalar < minimum
            if invalid:
                comparison = "greater than" if strict else "at least"
                raise ValueError(f"{name} must be {comparison} {minimum}")

        if not self.hidden_dims:
            raise ValueError("hidden_dims must contain positive widths")
        for width in self.hidden_dims:
            require_integer("hidden_dims entries", width, minimum=1)
        require_integer("time_embed_dim", self.time_embed_dim, minimum=2)
        require_real("learning_rate", self.learning_rate, minimum=0.0, strict=True)
        require_integer("training_steps", self.training_steps, minimum=1)
        require_integer("microbatch_size", self.microbatch_size, minimum=1)
        require_integer("effective_batch_size", self.effective_batch_size, minimum=1)
        require_real("weight_decay", self.weight_decay, minimum=0.0, strict=False)
        if self.effective_batch_size % self.microbatch_size != 0:
            raise ValueError("effective_batch_size must be divisible by microbatch_size")

    @property
    def accumulation_steps(self) -> int:
        """Number of equal-size microbatches in one Adam update."""
        return self.effective_batch_size // self.microbatch_size


class CrossFittedBaselineBatch(NamedTuple):
    """Stopped opposite-fold value predictions."""

    value: Array
    source_training_fold: Array
    finite: Array
    stopped: Array


class CriticAutodiffBatch(NamedTuple):
    """Stopped opposite-fold value predictions and state gradients."""

    value: Array
    costate: Array
    source_training_fold: Array
    finite: Array
    method: Array


@dataclass(frozen=True)
class CrossFittedValueCriticResult:
    """Complete two-fold train state and cross-fit assignment.

    ``params_by_training_fold[k]`` and ``optimizer_by_training_fold[k]`` were
    fit only on rows for which ``row_fold == k``.  Public prediction helpers
    intentionally select model ``1 - row_fold``.
    """

    params_by_training_fold: tuple[Params, Params]
    optimizer_by_training_fold: tuple[AdamState, AdamState]
    row_fold: Array
    loss_history: Array
    final_metrics: tuple[dict[str, Array], dict[str, Array]]
    state_dim: int
    context_dim: int
    policy_fingerprint: str
    dataset_fingerprint: str
    assignment_fingerprint: str
    fold_provenance_fingerprints: tuple[str, str]
    fold_state_fingerprints: tuple[str, str]
    next_key: PRNGKey


def _tree_all_finite(tree: Any) -> Array:
    leaves = jax.tree_util.tree_leaves(tree)
    if not leaves:
        return jnp.asarray(False)
    return jnp.all(jnp.stack([jnp.all(jnp.isfinite(jnp.asarray(x))) for x in leaves]))


def _critic_input(states: Array, endpoint_context: Array) -> Array:
    return jnp.concatenate([states, endpoint_context], axis=-1)


def _dataset_fingerprint(dataset: FixedPolicyReturnDataset) -> str:
    """Hash values and row order so a fold assignment cannot be misapplied."""
    digest = hashlib.sha256()
    digest.update(dataset.policy_fingerprint.encode("utf-8"))
    for name, value in (
        ("states", dataset.states),
        ("times", dataset.times),
        ("endpoint_context", dataset.endpoint_context),
        ("returns", dataset.returns),
    ):
        host = np.ascontiguousarray(np.asarray(jax.device_get(value)))
        digest.update(name.encode("utf-8"))
        digest.update(str(host.dtype).encode("ascii"))
        digest.update(np.asarray(host.shape, dtype=np.int64).tobytes())
        digest.update(host.tobytes())
    return digest.hexdigest()


def _assignment_fingerprint(dataset_fingerprint: str, row_fold: Array) -> str:
    """Bind the held-out assignment to the immutable dataset identity."""
    host = np.ascontiguousarray(np.asarray(jax.device_get(row_fold), dtype=np.int32))
    digest = hashlib.sha256(dataset_fingerprint.encode("ascii"))
    digest.update(np.asarray(host.shape, dtype=np.int64).tobytes())
    digest.update(host.tobytes())
    return digest.hexdigest()


def _update_digest_with_text(digest: Any, label: str, value: str) -> None:
    """Append a length-delimited text field to a provenance digest."""
    encoded_label = label.encode("utf-8")
    encoded_value = value.encode("utf-8")
    digest.update(len(encoded_label).to_bytes(8, "little"))
    digest.update(encoded_label)
    digest.update(len(encoded_value).to_bytes(8, "little"))
    digest.update(encoded_value)


def _update_digest_with_tree(digest: Any, label: str, tree: Any) -> None:
    """Hash pytree structure, leaf metadata, and every leaf byte exactly.

    This is deliberately a host-side checkpoint-integrity operation rather
    than a JAX kernel.  The result is stable across device placement, while
    preserving dtype, shape, leaf order, and all numerical values.
    """
    path_leaves, tree_def = jax.tree_util.tree_flatten_with_path(tree)
    _update_digest_with_text(digest, f"{label}:tree_def", str(tree_def))
    _update_digest_with_text(digest, f"{label}:leaf_count", str(len(path_leaves)))
    for index, (path, leaf) in enumerate(path_leaves):
        # ``path`` retains dictionary keys and sequence positions, so leaves
        # cannot be exchanged between structurally distinct locations.
        _update_digest_with_text(digest, f"{label}:path:{index}", repr(path))
        host = np.ascontiguousarray(np.asarray(jax.device_get(leaf)))
        _update_digest_with_text(digest, f"{label}:dtype:{index}", str(host.dtype))
        digest.update(np.asarray(host.shape, dtype=np.int64).tobytes())
        digest.update(host.tobytes())


def _fold_provenance_fingerprint(
    *,
    training_fold: int,
    policy_fingerprint: str,
    dataset_fingerprint: str,
    assignment_fingerprint: str,
    state_dim: int,
    context_dim: int,
    training_row_count: int,
    training_steps: int,
) -> str:
    """Bind one fitted model to the fold and immutable training provenance."""
    digest = hashlib.sha256()
    _update_digest_with_text(digest, "schema", "mam_value_critic_fold_provenance_v1")
    for label, value in (
        ("training_fold", str(training_fold)),
        ("policy_fingerprint", policy_fingerprint),
        ("dataset_fingerprint", dataset_fingerprint),
        ("assignment_fingerprint", assignment_fingerprint),
        ("state_dim", str(state_dim)),
        ("context_dim", str(context_dim)),
        ("training_row_count", str(training_row_count)),
        ("training_steps", str(training_steps)),
    ):
        _update_digest_with_text(digest, label, value)
    return digest.hexdigest()


def _fold_state_fingerprint(
    *,
    training_fold: int,
    provenance_fingerprint: str,
    params: Params,
    optimizer: AdamState,
) -> str:
    """Bind complete parameter and Adam state bytes to their declared fold."""
    digest = hashlib.sha256()
    _update_digest_with_text(digest, "schema", "mam_value_critic_fold_state_v1")
    _update_digest_with_text(digest, "training_fold", str(training_fold))
    _update_digest_with_text(digest, "provenance_fingerprint", provenance_fingerprint)
    _update_digest_with_tree(digest, "params", params)
    _update_digest_with_tree(digest, "optimizer_m", optimizer.m)
    _update_digest_with_tree(digest, "optimizer_v", optimizer.v)
    _update_digest_with_tree(digest, "optimizer_step", optimizer.step)
    return digest.hexdigest()


def _require_sha256_digest(name: str, value: Any) -> str:
    """Return a validated SHA-256 digest, failing closed for checkpoints."""
    if not isinstance(value, str) or len(value) != 64:
        raise ValueError(f"{name} must be a SHA-256 hex digest")
    try:
        int(value, 16)
    except ValueError as exc:
        raise ValueError(f"{name} must be a SHA-256 hex digest") from exc
    return value


def _critic_values(
    factory: NetworkFactory,
    params: Params,
    states: Array,
    times: Array,
    endpoint_context: Array,
) -> Array:
    output = jnp.asarray(
        factory.forward(params, _critic_input(states, endpoint_context), times),
        dtype=states.dtype,
    )
    expected = (states.shape[0], 1)
    if output.shape != expected:
        raise ValueError(f"value critic must return shape {expected}, got {output.shape}")
    return output[:, 0]


def cross_fitted_value_predictions(
    factory: NetworkFactory,
    params_by_training_fold: tuple[Params, Params],
    states: Array,
    times: Array,
    endpoint_context: Array,
    row_fold: Array,
) -> CrossFittedBaselineBatch:
    """Return stopped predictions from the model that did not see each row.

    This array-only kernel is JIT compatible.  Invalid fold labels or
    nonfinite model values yield NaNs and ``finite=False``; the high-level
    :class:`CrossFittedValueCritic` method synchronizes that flag and raises.
    """
    states = jnp.asarray(states)
    times = jnp.asarray(times, dtype=states.dtype)
    endpoint_context = jnp.asarray(endpoint_context, dtype=states.dtype)
    row_fold = jnp.asarray(row_fold)
    if states.ndim != 2:
        raise ValueError("states must have shape [batch,state_dim]")
    if times.shape != (states.shape[0],):
        raise ValueError("times must have shape [batch]")
    if endpoint_context.ndim != 2 or endpoint_context.shape[0] != states.shape[0]:
        raise ValueError("endpoint_context must have shape [batch,context_dim]")
    if row_fold.shape != (states.shape[0],):
        raise ValueError("row_fold must have shape [batch]")

    value0 = _critic_values(factory, params_by_training_fold[0], states, times, endpoint_context)
    value1 = _critic_values(factory, params_by_training_fold[1], states, times, endpoint_context)
    valid_fold = (row_fold == 0) | (row_fold == 1)
    source = 1 - row_fold.astype(jnp.int32)
    # Fold-zero rows are held out from model one, and conversely.
    selected = jnp.where(row_fold == 0, value1, value0)
    input_finite = (
        jnp.all(jnp.isfinite(states), axis=-1)
        & jnp.isfinite(times)
        & jnp.all(jnp.isfinite(endpoint_context), axis=-1)
    )
    params0_finite = _tree_all_finite(params_by_training_fold[0])
    params1_finite = _tree_all_finite(params_by_training_fold[1])
    selected_params_finite = jnp.where(row_fold == 0, params1_finite, params0_finite)
    finite = valid_fold & input_finite & selected_params_finite & jnp.isfinite(selected)
    selected = jnp.where(finite, selected, jnp.full_like(selected, jnp.nan))
    return CrossFittedBaselineBatch(
        value=jax.lax.stop_gradient(selected),
        source_training_fold=source,
        finite=finite,
        stopped=jnp.asarray(True),
    )


def cross_fitted_critic_autodiff(
    factory: NetworkFactory,
    params_by_training_fold: tuple[Params, Params],
    states: Array,
    times: Array,
    endpoint_context: Array,
    row_fold: Array,
) -> CriticAutodiffBatch:
    """Differentiate the opposite-fold scalar critic with respect to state.

    The endpoint and time inputs are held fixed.  Both the returned value and
    costate are stopped so they can be used as evaluation targets without
    accidentally backpropagating into the critic parameters.
    """
    baseline = cross_fitted_value_predictions(
        factory,
        params_by_training_fold,
        states,
        times,
        endpoint_context,
        row_fold,
    )
    states = jnp.asarray(states)
    times = jnp.asarray(times, dtype=states.dtype)
    endpoint_context = jnp.asarray(endpoint_context, dtype=states.dtype)
    row_fold = jnp.asarray(row_fold)

    def one_costate(
        params: Params,
        state: Array,
        time: Array,
        context: Array,
    ) -> Array:
        def scalar_value(variable_state: Array) -> Array:
            output = jnp.asarray(
                factory.forward(
                    params,
                    _critic_input(variable_state[None, :], context[None, :]),
                    time[None],
                ),
                dtype=variable_state.dtype,
            )
            if output.shape != (1, 1):
                raise ValueError(f"value critic must return shape (1, 1), got {output.shape}")
            return output[0, 0]

        return jnp.asarray(jax.grad(scalar_value)(state))

    costate0 = jax.vmap(one_costate, in_axes=(None, 0, 0, 0))(
        params_by_training_fold[0], states, times, endpoint_context
    )
    costate1 = jax.vmap(one_costate, in_axes=(None, 0, 0, 0))(
        params_by_training_fold[1], states, times, endpoint_context
    )
    costate = jnp.where((row_fold == 0)[:, None], costate1, costate0)
    finite = baseline.finite & jnp.all(jnp.isfinite(costate), axis=-1)
    costate = jnp.where(finite[:, None], costate, jnp.full_like(costate, jnp.nan))
    return CriticAutodiffBatch(
        value=baseline.value,
        costate=jax.lax.stop_gradient(costate),
        source_training_fold=baseline.source_training_fold,
        finite=finite,
        method=jnp.asarray(CRITIC_AUTODIFF_METHOD, dtype=jnp.int32),
    )


class CrossFittedValueCritic:
    """Train and evaluate a two-fold scalar fixed-policy value critic."""

    def __init__(self, config: ValueCriticConfig | None = None):
        self.config = config or ValueCriticConfig()
        self.factory: NetworkFactory = self.config.network_factory or MLPFactory(
            hidden_dims=self.config.hidden_dims,
            time_embed_dim=self.config.time_embed_dim,
        )
        self._update = jax.jit(self._make_accumulated_update())

    def _make_accumulated_update(self):
        factory = self.factory
        learning_rate = self.config.learning_rate
        weight_decay = self.config.weight_decay
        accumulation_steps = self.config.accumulation_steps

        def microbatch_loss(
            params: Params,
            states: Array,
            times: Array,
            context: Array,
            targets: Array,
        ) -> tuple[Array, Array]:
            prediction = _critic_values(factory, params, states, times, context)
            stopped_targets = jax.lax.stop_gradient(targets)
            residual = prediction - stopped_targets
            loss = jnp.mean(residual**2)
            finite = (
                jnp.all(jnp.isfinite(prediction))
                & jnp.all(jnp.isfinite(stopped_targets))
                & jnp.isfinite(loss)
            )
            return loss, finite

        def update(
            params: Params,
            optimizer: AdamState,
            states: Array,
            times: Array,
            context: Array,
            targets: Array,
        ) -> tuple[Params, AdamState, dict[str, Array]]:
            zero_gradients = jax.tree_util.tree_map(jnp.zeros_like, params)
            initial = (
                zero_gradients,
                jnp.asarray(0.0, dtype=states.dtype),
                jnp.asarray(True),
            )

            def scan_step(carry, batch):
                gradient_sum, loss_sum, finite = carry
                batch_states, batch_times, batch_context, batch_targets = batch
                (loss, prediction_finite), gradients = jax.value_and_grad(
                    microbatch_loss, has_aux=True
                )(
                    params,
                    batch_states,
                    batch_times,
                    batch_context,
                    batch_targets,
                )
                gradient_sum = jax.tree_util.tree_map(jnp.add, gradient_sum, gradients)
                finite = finite & prediction_finite & _tree_all_finite(gradients)
                return (gradient_sum, loss_sum + loss, finite), None

            (gradient_sum, loss_sum, finite), _ = jax.lax.scan(
                scan_step,
                initial,
                (states, times, context, targets),
            )
            denominator = jnp.asarray(accumulation_steps, dtype=states.dtype)
            gradients = jax.tree_util.tree_map(
                lambda value: value / denominator,
                gradient_sum,
            )
            candidate_params, candidate_optimizer = adam_update(
                optimizer,
                gradients,
                params,
                lr=learning_rate,
                weight_decay=weight_decay,
            )
            valid_update = (
                finite
                & _tree_all_finite(params)
                & _tree_all_finite(optimizer)
                & _tree_all_finite(gradients)
                & _tree_all_finite(candidate_params)
                & _tree_all_finite(candidate_optimizer)
            )
            # Keep the original state on device when an invalid candidate is
            # encountered; the host wrapper then raises before continuing.
            new_params = jax.tree_util.tree_map(
                lambda candidate, old: jnp.where(valid_update, candidate, old),
                candidate_params,
                params,
            )
            new_optimizer = jax.tree_util.tree_map(
                lambda candidate, old: jnp.where(valid_update, candidate, old),
                candidate_optimizer,
                optimizer,
            )
            metrics = {
                "loss": loss_sum / denominator,
                "gradient_finite": _tree_all_finite(gradients),
                "parameters_finite": _tree_all_finite(candidate_params),
                "optimizer_finite": _tree_all_finite(candidate_optimizer),
                "valid_update": valid_update,
            }
            return new_params, new_optimizer, metrics

        return update

    def _init_params(self, key: PRNGKey, input_dim: int, dtype: Any) -> Params:
        sanity_key, init_key = jax.random.split(key)
        try:
            sanity_check(self.factory, sanity_key, input_dim, 1)
        except AssertionError as exc:
            if "NaN/Inf" in str(exc):
                raise FloatingPointError(
                    "nonfinite value-critic factory output or gradient"
                ) from exc
            raise ValueError(f"invalid value-critic factory: {exc}") from exc
        params: Params = self.factory.init(init_key, input_dim, 1)
        params = jax.tree_util.tree_map(lambda value: jnp.asarray(value, dtype=dtype), params)
        if not bool(np.asarray(jax.device_get(_tree_all_finite(params)))):
            raise FloatingPointError("value-critic initialization is nonfinite")
        return params

    def fit(
        self,
        key: PRNGKey,
        dataset: FixedPolicyReturnDataset,
        *,
        row_fold: Array | None = None,
    ) -> CrossFittedValueCriticResult:
        """Fit two models to disjoint folds of one frozen-policy cache.

        Sampling within a training fold is with replacement.  Each Adam step
        averages ``effective_batch_size / microbatch_size`` equal-size
        microbatch gradients before applying one update.
        """
        state_dim, context_dim, row_count = self._validate_dataset(dataset)
        (
            assignment_key,
            init0_key,
            init1_key,
            train0_key,
            train1_key,
            next_key,
        ) = jax.random.split(key, 6)
        if row_fold is None:
            permutation = jax.random.permutation(assignment_key, row_count)
            row_fold = jnp.ones((row_count,), dtype=jnp.int32)
            row_fold = row_fold.at[permutation[: row_count // 2]].set(0)
        row_fold = self._validate_folds(row_fold, row_count)

        input_dim = state_dim + context_dim
        params0 = self._init_params(init0_key, input_dim, dataset.states.dtype)
        params1 = self._init_params(init1_key, input_dim, dataset.states.dtype)
        params0, optimizer0, history0, metrics0 = self._train_fold(
            train0_key, params0, dataset, row_fold, training_fold=0
        )
        params1, optimizer1, history1, metrics1 = self._train_fold(
            train1_key, params1, dataset, row_fold, training_fold=1
        )
        dataset_fingerprint = _dataset_fingerprint(dataset)
        assignment_fingerprint = _assignment_fingerprint(dataset_fingerprint, row_fold)
        training_row_counts = tuple(
            int(np.asarray(jax.device_get(metrics["training_row_count"])))
            for metrics in (metrics0, metrics1)
        )
        fold_provenance_fingerprints: tuple[str, str] = (
            _fold_provenance_fingerprint(
                training_fold=0,
                policy_fingerprint=dataset.policy_fingerprint,
                dataset_fingerprint=dataset_fingerprint,
                assignment_fingerprint=assignment_fingerprint,
                state_dim=state_dim,
                context_dim=context_dim,
                training_row_count=training_row_counts[0],
                training_steps=self.config.training_steps,
            ),
            _fold_provenance_fingerprint(
                training_fold=1,
                policy_fingerprint=dataset.policy_fingerprint,
                dataset_fingerprint=dataset_fingerprint,
                assignment_fingerprint=assignment_fingerprint,
                state_dim=state_dim,
                context_dim=context_dim,
                training_row_count=training_row_counts[1],
                training_steps=self.config.training_steps,
            ),
        )
        fold_state_fingerprints: tuple[str, str] = (
            _fold_state_fingerprint(
                training_fold=0,
                provenance_fingerprint=fold_provenance_fingerprints[0],
                params=params0,
                optimizer=optimizer0,
            ),
            _fold_state_fingerprint(
                training_fold=1,
                provenance_fingerprint=fold_provenance_fingerprints[1],
                params=params1,
                optimizer=optimizer1,
            ),
        )
        return CrossFittedValueCriticResult(
            params_by_training_fold=(params0, params1),
            optimizer_by_training_fold=(optimizer0, optimizer1),
            row_fold=row_fold,
            loss_history=jnp.stack([history0, history1]),
            final_metrics=(metrics0, metrics1),
            state_dim=state_dim,
            context_dim=context_dim,
            policy_fingerprint=dataset.policy_fingerprint,
            dataset_fingerprint=dataset_fingerprint,
            assignment_fingerprint=assignment_fingerprint,
            fold_provenance_fingerprints=fold_provenance_fingerprints,
            fold_state_fingerprints=fold_state_fingerprints,
            next_key=next_key,
        )

    def _train_fold(
        self,
        key: PRNGKey,
        params: Params,
        dataset: FixedPolicyReturnDataset,
        row_fold: Array,
        *,
        training_fold: int,
    ) -> tuple[Params, AdamState, Array, dict[str, Array]]:
        host_folds = np.asarray(jax.device_get(row_fold))
        training_indices = jnp.asarray(np.flatnonzero(host_folds == training_fold), dtype=jnp.int32)
        optimizer = init_adam(params)
        losses: list[Array] = []
        metrics: dict[str, Array] = {}
        shape = (self.config.accumulation_steps, self.config.microbatch_size)
        for _ in range(self.config.training_steps):
            key, sampling_key = jax.random.split(key)
            local_indices = jax.random.randint(
                sampling_key,
                shape,
                minval=0,
                maxval=training_indices.shape[0],
            )
            indices = training_indices[local_indices]
            params, optimizer, metrics = self._update(
                params,
                optimizer,
                dataset.states[indices],
                dataset.times[indices],
                dataset.endpoint_context[indices],
                dataset.returns[indices],
            )
            if not bool(np.asarray(jax.device_get(metrics["valid_update"]))):
                raise FloatingPointError(
                    f"nonfinite value-critic update in training fold {training_fold}"
                )
            losses.append(metrics["loss"])
        metrics = {
            **metrics,
            "training_fold": jnp.asarray(training_fold, dtype=jnp.int32),
            "training_row_count": jnp.asarray(training_indices.shape[0], dtype=jnp.int32),
        }
        return params, optimizer, jnp.stack(losses), metrics

    def cross_fitted_baseline(
        self,
        result: CrossFittedValueCriticResult,
        dataset: FixedPolicyReturnDataset,
    ) -> CrossFittedBaselineBatch:
        """Evaluate stopped opposite-fold baselines in the original row order."""
        self._validate_result_dataset(result, dataset)
        batch = cross_fitted_value_predictions(
            self.factory,
            result.params_by_training_fold,
            dataset.states,
            dataset.times,
            dataset.endpoint_context,
            result.row_fold,
        )
        if not bool(np.asarray(jax.device_get(jnp.all(batch.finite)))):
            raise FloatingPointError("cross-fitted value baseline is nonfinite")
        return batch

    def critic_autodiff_comparison(
        self,
        result: CrossFittedValueCriticResult,
        dataset: FixedPolicyReturnDataset,
    ) -> CriticAutodiffBatch:
        """Evaluate the mandatory opposite-fold critic-autodiff costate."""
        self._validate_result_dataset(result, dataset)
        batch = cross_fitted_critic_autodiff(
            self.factory,
            result.params_by_training_fold,
            dataset.states,
            dataset.times,
            dataset.endpoint_context,
            result.row_fold,
        )
        if not bool(np.asarray(jax.device_get(jnp.all(batch.finite)))):
            raise FloatingPointError("cross-fitted critic-autodiff costate is nonfinite")
        return batch

    @staticmethod
    def _validate_dataset(
        dataset: FixedPolicyReturnDataset,
    ) -> tuple[int, int, int]:
        states = jnp.asarray(dataset.states)
        times = jnp.asarray(dataset.times)
        context = jnp.asarray(dataset.endpoint_context)
        returns = jnp.asarray(dataset.returns)
        if states.ndim != 2 or states.shape[0] < 2:
            raise ValueError("states must have shape [batch,state_dim] with batch >= 2")
        row_count, state_dim = states.shape
        if state_dim < 1:
            raise ValueError("state_dim must be positive")
        if times.shape != (row_count,):
            raise ValueError("times must have shape [batch]")
        if context.ndim != 2 or context.shape[0] != row_count:
            raise ValueError("endpoint_context must have shape [batch,context_dim]")
        if returns.shape != (row_count,):
            raise ValueError("returns must have shape [batch]")
        for name, value in (
            ("states", states),
            ("times", times),
            ("endpoint_context", context),
            ("returns", returns),
        ):
            if not jnp.issubdtype(value.dtype, jnp.inexact):
                raise TypeError(f"{name} must have an inexact dtype")
            if not bool(np.asarray(jax.device_get(jnp.all(jnp.isfinite(value))))):
                raise FloatingPointError(f"{name} contains a nonfinite value")
        if not isinstance(dataset.policy_fingerprint, str) or not dataset.policy_fingerprint:
            raise ValueError("policy_fingerprint must be a nonempty string")
        return state_dim, context.shape[1], row_count

    @staticmethod
    def _validate_folds(row_fold: Array, row_count: int) -> Array:
        row_fold = jnp.asarray(row_fold)
        if row_fold.shape != (row_count,):
            raise ValueError("row_fold must have shape [batch]")
        if row_fold.dtype == jnp.dtype(jnp.bool_) or not jnp.issubdtype(
            row_fold.dtype, jnp.integer
        ):
            raise TypeError("row_fold must have an integer dtype")
        host = np.asarray(jax.device_get(row_fold))
        if not np.all((host == 0) | (host == 1)):
            raise ValueError("row_fold entries must be zero or one")
        if not np.any(host == 0) or not np.any(host == 1):
            raise ValueError("both cross-fitting folds must be nonempty")
        return row_fold.astype(jnp.int32)

    def _validate_result_dataset(
        self,
        result: CrossFittedValueCriticResult,
        dataset: FixedPolicyReturnDataset,
    ) -> None:
        state_dim, context_dim, row_count = self._validate_dataset(dataset)
        if state_dim != result.state_dim or context_dim != result.context_dim:
            raise ValueError("dataset dimensions differ from the fitted critic")
        if row_count != result.row_fold.shape[0]:
            raise ValueError("dataset row count differs from the cross-fit assignment")
        if dataset.policy_fingerprint != result.policy_fingerprint:
            raise ValueError("policy fingerprint differs from the fitted critic")
        if _dataset_fingerprint(dataset) != result.dataset_fingerprint:
            raise ValueError(
                "dataset values or row order differ from the fitted cross-fit assignment"
            )
        row_fold = self._validate_folds(result.row_fold, row_count)
        if (
            _assignment_fingerprint(result.dataset_fingerprint, row_fold)
            != result.assignment_fingerprint
        ):
            raise ValueError("cross-fit assignment fingerprint mismatch")
        self._validate_fold_state_bindings(result, row_fold)

    def _validate_fold_state_bindings(
        self,
        result: CrossFittedValueCriticResult,
        row_fold: Array,
    ) -> None:
        """Fail closed if a model/Adam pair is moved to the other fold.

        This validation is intentionally independent of the critic factory:
        both prediction entry points and checkpoint restoration need to reject
        a syntactically valid but semantically swapped fold pair.
        """
        if (
            not isinstance(result.params_by_training_fold, tuple)
            or len(result.params_by_training_fold) != 2
        ):
            raise ValueError("value critic must contain exactly two parameter trees")
        if (
            not isinstance(result.optimizer_by_training_fold, tuple)
            or len(result.optimizer_by_training_fold) != 2
        ):
            raise ValueError("value critic must contain exactly two optimizer states")
        if (
            not isinstance(result.fold_provenance_fingerprints, tuple)
            or len(result.fold_provenance_fingerprints) != 2
        ):
            raise ValueError("value critic must contain exactly two fold provenance fingerprints")
        if (
            not isinstance(result.fold_state_fingerprints, tuple)
            or len(result.fold_state_fingerprints) != 2
        ):
            raise ValueError("value critic must contain exactly two fold state fingerprints")

        dataset_fingerprint = _require_sha256_digest(
            "dataset_fingerprint", result.dataset_fingerprint
        )
        assignment_fingerprint = _require_sha256_digest(
            "assignment_fingerprint", result.assignment_fingerprint
        )
        host_folds = np.asarray(jax.device_get(row_fold))
        for fold, (params, optimizer, provenance, state) in enumerate(
            zip(
                result.params_by_training_fold,
                result.optimizer_by_training_fold,
                result.fold_provenance_fingerprints,
                result.fold_state_fingerprints,
                strict=True,
            )
        ):
            if not isinstance(optimizer, AdamState):
                raise TypeError(f"fold {fold} optimizer has the wrong type")
            provenance = _require_sha256_digest(f"fold {fold} provenance fingerprint", provenance)
            state = _require_sha256_digest(f"fold {fold} state fingerprint", state)
            expected_provenance = _fold_provenance_fingerprint(
                training_fold=fold,
                policy_fingerprint=result.policy_fingerprint,
                dataset_fingerprint=dataset_fingerprint,
                assignment_fingerprint=assignment_fingerprint,
                state_dim=result.state_dim,
                context_dim=result.context_dim,
                training_row_count=int(np.sum(host_folds == fold)),
                training_steps=self.config.training_steps,
            )
            if provenance != expected_provenance:
                raise ValueError(f"fold {fold} provenance fingerprint mismatch")
            expected_state = _fold_state_fingerprint(
                training_fold=fold,
                provenance_fingerprint=provenance,
                params=params,
                optimizer=optimizer,
            )
            if state != expected_state:
                raise ValueError(f"fold {fold} state fingerprint mismatch")

    def validate_result_state(
        self,
        result: CrossFittedValueCriticResult,
        *,
        state_dim: int,
        context_dim: int,
        row_count: int,
    ) -> None:
        """Validate a checkpointed critic result without its discarded dataset.

        The dataset values cannot be reconstructed from the result, but its
        recorded digest is bound to the exact fold assignment.  Model and Adam
        trees are checked against a fresh factory initialization, and every
        run-length-dependent array is checked against this critic's config.
        """
        if not isinstance(result, CrossFittedValueCriticResult):
            raise TypeError("value critic checkpoint has the wrong result type")
        if result.state_dim != state_dim or result.context_dim != context_dim:
            raise ValueError("value critic checkpoint dimensions mismatch")
        if isinstance(row_count, bool) or not isinstance(row_count, (int, np.integer)):
            raise TypeError("value critic row_count must be an integer")
        if row_count < 2:
            raise ValueError("value critic row_count must be at least two")
        row_fold = self._validate_folds(result.row_fold, int(row_count))

        dataset_fingerprint = _require_sha256_digest(
            "dataset_fingerprint",
            result.dataset_fingerprint,
        )
        _require_sha256_digest("assignment_fingerprint", result.assignment_fingerprint)
        if _assignment_fingerprint(dataset_fingerprint, row_fold) != result.assignment_fingerprint:
            raise ValueError("cross-fit assignment fingerprint mismatch")
        if not isinstance(result.policy_fingerprint, str) or not result.policy_fingerprint:
            raise ValueError("policy_fingerprint must be a nonempty string")

        if (
            not isinstance(result.params_by_training_fold, tuple)
            or len(result.params_by_training_fold) != 2
        ):
            raise ValueError("value critic must contain exactly two parameter trees")
        if (
            not isinstance(result.optimizer_by_training_fold, tuple)
            or len(result.optimizer_by_training_fold) != 2
        ):
            raise ValueError("value critic must contain exactly two optimizer states")
        template = self._init_params(
            jax.random.PRNGKey(0),
            state_dim + context_dim,
            jnp.float32,
        )
        template_structure = jax.tree_util.tree_structure(template)
        template_leaves = jax.tree_util.tree_leaves(template)

        def validate_tree(name: str, tree: Any) -> None:
            if jax.tree_util.tree_structure(tree) != template_structure:
                raise ValueError(f"{name} tree differs from the critic factory")
            leaves = jax.tree_util.tree_leaves(tree)
            for leaf, expected in zip(leaves, template_leaves, strict=True):
                value = np.asarray(jax.device_get(leaf))
                expected_value = np.asarray(jax.device_get(expected))
                if value.shape != expected_value.shape or value.dtype != np.dtype(np.float32):
                    raise ValueError(f"{name} shape/dtype differs from the critic factory")
                if not np.all(np.isfinite(value)):
                    raise FloatingPointError(f"{name} contains a nonfinite value")

        for fold, (params, optimizer) in enumerate(
            zip(
                result.params_by_training_fold,
                result.optimizer_by_training_fold,
                strict=True,
            )
        ):
            validate_tree(f"fold {fold} parameters", params)
            if not isinstance(optimizer, AdamState):
                raise TypeError(f"fold {fold} optimizer has the wrong type")
            validate_tree(f"fold {fold} Adam first moment", optimizer.m)
            validate_tree(f"fold {fold} Adam second moment", optimizer.v)
            step = np.asarray(jax.device_get(optimizer.step))
            if step.shape != () or not np.issubdtype(step.dtype, np.integer):
                raise TypeError(f"fold {fold} Adam step must be an integer scalar")
            if int(step) != self.config.training_steps:
                raise ValueError(f"fold {fold} Adam step differs from training_steps")

        history = np.asarray(jax.device_get(result.loss_history))
        expected_history_shape = (2, self.config.training_steps)
        if history.shape != expected_history_shape or history.dtype != np.dtype(np.float32):
            raise ValueError("value critic loss history shape/dtype mismatch")
        if not np.all(np.isfinite(history)):
            raise FloatingPointError("value critic loss history is nonfinite")
        if not isinstance(result.final_metrics, tuple) or len(result.final_metrics) != 2:
            raise ValueError("value critic final metrics must contain two folds")
        expected_metric_fields = {
            "loss",
            "gradient_finite",
            "parameters_finite",
            "optimizer_finite",
            "valid_update",
            "training_fold",
            "training_row_count",
        }
        host_folds = np.asarray(jax.device_get(row_fold))
        for fold, metrics in enumerate(result.final_metrics):
            if not isinstance(metrics, dict) or set(metrics) != expected_metric_fields:
                raise ValueError("value critic final metric schema mismatch")
            if not bool(np.asarray(jax.device_get(_tree_all_finite(metrics)))):
                raise FloatingPointError("value critic final metrics are nonfinite")
            if int(np.asarray(jax.device_get(metrics["training_fold"]))) != fold:
                raise ValueError("value critic final metric fold mismatch")
            expected_rows = int(np.sum(host_folds == fold))
            if int(np.asarray(jax.device_get(metrics["training_row_count"]))) != expected_rows:
                raise ValueError("value critic final metric row count mismatch")
            for flag in (
                "gradient_finite",
                "parameters_finite",
                "optimizer_finite",
                "valid_update",
            ):
                if not bool(np.asarray(jax.device_get(metrics[flag]))):
                    raise ValueError(f"value critic final metric {flag} is false")
        try:
            jax.random.split(result.next_key)
        except (TypeError, ValueError) as exc:
            raise ValueError("value critic next_key is invalid") from exc
        self._validate_fold_state_bindings(result, row_fold)


__all__ = [
    "CRITIC_AUTODIFF_METHOD",
    "CriticAutodiffBatch",
    "CrossFittedBaselineBatch",
    "CrossFittedValueCritic",
    "CrossFittedValueCriticResult",
    "FixedPolicyReturnDataset",
    "ValueCriticConfig",
    "cross_fitted_critic_autodiff",
    "cross_fitted_value_predictions",
]
