"""HyperSINDy: Sparse Identification of Stochastic Dynamics via Hypernetworks.

This module implements HyperSINDy for learning sparse, interpretable
representations of stochastic dynamics.

Mathematical Background:
=======================
HyperSINDy models the SDE:
    dX = Θ(X) ξ(z) dt + σ dW

where:
- Θ(X) is a dictionary of candidate nonlinear functions
- ξ(z) are sparse coefficients generated by a hypernetwork from latent z
- z is sampled from a learned variational distribution

The sparsity is enforced via a learnable binary mask (hard concrete).

Key Features:
============
1. **Sparse & Interpretable**: Discovers parsimonious governing equations
2. **Uncertainty Quantification**: Hypernetwork generates distribution over models
3. **Stochastic Extension**: Properly handles SDEs (unlike standard SINDy)
4. **Scalable**: Works in high dimensions via variational inference

For Schrödinger Bridge:
======================
HyperSINDy can learn the SB drift as a sparse combination of dictionary terms:
    b*(x,t) = b_ref(x,t) + σ² Θ(x,t) ξ

This gives interpretable and fast-to-evaluate drift functions.

Reference:
=========
Jacobs et al. (2023) "HyperSINDy: Deep Generative Modeling of Nonlinear
Stochastic Governing Equations" (arXiv:2310.04832)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Dict, List, NamedTuple, Optional, Tuple, Union

import jax
import jax.numpy as jnp
from jax.scipy.special import logsumexp

from .dictionary import Dictionary, PolynomialDictionary

# Type aliases
Array = jnp.ndarray
PRNGKey = jax.Array
Scalar = Union[float, Array]
Params = Dict[str, Array]


# =============================================================================
# Configuration
# =============================================================================

@dataclass
class HyperSINDyConfig:
    """Configuration for HyperSINDy.
    
    Attributes:
        latent_dim: Dimension of the latent space z.
        encoder_hidden_dims: Hidden dimensions for encoder.
        hypernetwork_hidden_dims: Hidden dimensions for hypernetwork.
        sparsity_temperature: Temperature for hard concrete (lower = sparser).
        sparsity_lambda: L0 regularization weight.
        kl_weight: Weight for KL divergence term.
        learning_rate: Learning rate.
        use_time_conditioning: Whether to condition on time t.
    """
    latent_dim: int = 32
    encoder_hidden_dims: Tuple[int, ...] = (128, 64)
    hypernetwork_hidden_dims: Tuple[int, ...] = (64, 64)
    sparsity_temperature: float = 0.5
    sparsity_lambda: float = 0.1
    kl_weight: float = 0.01
    learning_rate: float = 1e-3
    use_time_conditioning: bool = True


# =============================================================================
# Sparsity Mask (Hard Concrete)
# =============================================================================

class SparsityMask:
    """Learnable sparsity mask using Hard Concrete distribution.
    
    The Hard Concrete distribution is a relaxation of Bernoulli that:
    1. Allows gradients to flow (unlike hard 0/1)
    2. Concentrates mass at exactly 0 and 1
    3. Temperature controls hardness
    
    Sampling: z ~ HardConcrete(log_α, β)
        u ~ Uniform(0, 1)
        s = sigmoid((log(u) - log(1-u) + log_α) / β)
        z̄ = s(ζ - γ) + γ
        z = min(1, max(0, z̄))
    """
    
    def __init__(
        self,
        num_terms: int,
        temperature: float = 0.5,
        gamma: float = -0.1,
        zeta: float = 1.1,
    ):
        self.num_terms = num_terms
        self.temperature = temperature
        self.gamma = gamma
        self.zeta = zeta
    
    def init_params(self, key: PRNGKey) -> Params:
        """Initialize mask parameters (log_alpha for each term)."""
        # Initialize to favor all terms active initially
        log_alpha = jax.random.uniform(key, (self.num_terms,), minval=0.0, maxval=0.5)
        return {'log_alpha': log_alpha}
    
    def sample(self, params: Params, key: PRNGKey, hard: bool = False) -> Array:
        """Sample from the hard concrete distribution.
        
        Args:
            params: Mask parameters with 'log_alpha'.
            key: Random key.
            hard: If True, return hard 0/1 values.
            
        Returns:
            Mask values, shape [num_terms].
        """
        log_alpha = params['log_alpha']
        
        if hard:
            # Hard threshold at 0.5 probability
            return (jax.nn.sigmoid(log_alpha) > 0.5).astype(jnp.float32)
        
        # Sample from uniform
        u = jax.random.uniform(key, log_alpha.shape, minval=1e-8, maxval=1-1e-8)
        
        # Concrete distribution
        s = jax.nn.sigmoid(
            (jnp.log(u) - jnp.log(1 - u) + log_alpha) / self.temperature
        )
        
        # Stretch and clamp
        z_bar = s * (self.zeta - self.gamma) + self.gamma
        z = jnp.clip(z_bar, 0.0, 1.0)
        
        return z
    
    def l0_penalty(self, params: Params) -> Scalar:
        """Compute expected L0 norm (number of active terms).
        
        E[z > 0] = sigmoid(log_alpha - β log(-γ/ζ))
        """
        log_alpha = params['log_alpha']
        
        # Probability of being non-zero
        prob_nonzero = jax.nn.sigmoid(
            log_alpha - self.temperature * jnp.log(-self.gamma / self.zeta)
        )
        
        return jnp.sum(prob_nonzero)
    
    def get_active_terms(self, params: Params, threshold: float = 0.5) -> Array:
        """Get indices of active (non-zero) terms."""
        probs = jax.nn.sigmoid(params['log_alpha'])
        return jnp.where(probs > threshold)[0]


# =============================================================================
# HyperSINDy Parameters
# =============================================================================

class HyperSINDyParams(NamedTuple):
    """HyperSINDy parameter container."""
    encoder: Params      # Variational encoder q(z|x, dx/dt)
    hypernetwork: Params # Maps z → coefficients ξ
    mask: Params         # Sparsity mask parameters
    prior: Params        # Prior parameters for latent z


def _init_mlp_params(
    key: PRNGKey,
    layer_dims: Tuple[int, ...],
) -> List[Params]:
    """Initialize MLP parameters."""
    params = []
    keys = jax.random.split(key, len(layer_dims) - 1)
    
    for i, (in_dim, out_dim) in enumerate(zip(layer_dims[:-1], layer_dims[1:])):
        fan_in = in_dim
        limit = jnp.sqrt(6.0 / (fan_in + out_dim))
        w = jax.random.uniform(keys[i], (in_dim, out_dim), minval=-limit, maxval=limit)
        b = jnp.zeros(out_dim)
        params.append({'w': w, 'b': b})
    
    return params


def _mlp_forward(params: List[Params], x: Array, activation: str = 'relu') -> Array:
    """MLP forward pass."""
    act_fn = jax.nn.relu if activation == 'relu' else jax.nn.tanh
    
    for i, layer in enumerate(params):
        x = x @ layer['w'] + layer['b']
        if i < len(params) - 1:  # No activation on last layer
            x = act_fn(x)
    return x


# =============================================================================
# HyperSINDy Core Functions
# =============================================================================

def init_hypersindy(
    key: PRNGKey,
    dictionary: Dictionary,
    output_dim: int,
    config: HyperSINDyConfig,
) -> HyperSINDyParams:
    """Initialize HyperSINDy parameters.
    
    Args:
        key: Random key.
        dictionary: Observable dictionary (determines num_terms).
        output_dim: Output dimension (state dimension).
        config: HyperSINDy configuration.
        
    Returns:
        Initialized parameters.
    """
    k1, k2, k3, k4 = jax.random.split(key, 4)
    
    num_terms = dictionary.size
    latent_dim = config.latent_dim
    
    # Encoder: (x, dx/dt, t) → (μ_z, log_σ_z)
    # Input: state + derivative + time (if used)
    encoder_input_dim = 2 * output_dim + (1 if config.use_time_conditioning else 0)
    encoder_dims = (encoder_input_dim,) + config.encoder_hidden_dims + (2 * latent_dim,)
    encoder_params = _init_mlp_params(k1, encoder_dims)
    
    # Hypernetwork: z → ξ (coefficients)
    # Output: num_terms * output_dim coefficients
    hypernet_output_dim = num_terms * output_dim
    hypernet_dims = (latent_dim,) + config.hypernetwork_hidden_dims + (hypernet_output_dim,)
    hypernetwork_params = _init_mlp_params(k2, hypernet_dims)
    
    # Sparsity mask
    mask = SparsityMask(num_terms, config.sparsity_temperature)
    mask_params = mask.init_params(k3)
    
    # Prior: standard Gaussian
    prior_params = {
        'mu': jnp.zeros(latent_dim),
        'log_sigma': jnp.zeros(latent_dim),
    }
    
    return HyperSINDyParams(
        encoder=encoder_params,
        hypernetwork=hypernetwork_params,
        mask=mask_params,
        prior=prior_params,
    )


def hypersindy_encode(
    params: HyperSINDyParams,
    x: Array,
    dx_dt: Array,
    t: Optional[Array] = None,
    config: HyperSINDyConfig = None,
) -> Tuple[Array, Array]:
    """Encode state and derivative to latent distribution parameters.
    
    Args:
        params: HyperSINDy parameters.
        x: State, shape [batch, dim].
        dx_dt: Time derivative, shape [batch, dim].
        t: Optional time, shape [batch] or [batch, 1].
        config: Configuration.
        
    Returns:
        (mu, log_sigma) for latent distribution.
    """
    # Concatenate inputs
    inputs = [x, dx_dt]
    if t is not None and (config is None or config.use_time_conditioning):
        t = jnp.atleast_2d(t)
        if t.shape[-1] != 1:
            t = t.reshape(-1, 1)
        inputs.append(t)
    
    encoder_input = jnp.concatenate(inputs, axis=-1)
    
    # Forward through encoder
    output = _mlp_forward(params.encoder, encoder_input)
    
    # Split into mu and log_sigma
    latent_dim = output.shape[-1] // 2
    mu = output[..., :latent_dim]
    log_sigma = output[..., latent_dim:]
    
    # Clamp log_sigma for stability
    log_sigma = jnp.clip(log_sigma, -10, 2)
    
    return mu, log_sigma


def hypersindy_sample_z(
    mu: Array,
    log_sigma: Array,
    key: PRNGKey,
) -> Array:
    """Sample from latent distribution using reparameterization."""
    eps = jax.random.normal(key, mu.shape)
    return mu + jnp.exp(log_sigma) * eps


def hypersindy_decode(
    params: HyperSINDyParams,
    z: Array,
    mask_key: PRNGKey,
    output_dim: int,
    hard_mask: bool = False,
) -> Tuple[Array, Array]:
    """Decode latent z to sparse coefficients.
    
    Args:
        params: HyperSINDy parameters.
        z: Latent vector, shape [batch, latent_dim].
        mask_key: Random key for mask sampling.
        output_dim: State dimension.
        hard_mask: Whether to use hard (0/1) mask.
        
    Returns:
        (coefficients, mask) where coefficients shape is [batch, num_terms, dim].
    """
    batch_size = z.shape[0] if z.ndim > 1 else 1
    z = jnp.atleast_2d(z)
    
    # Get raw coefficients from hypernetwork
    raw_coeffs = _mlp_forward(params.hypernetwork, z)  # [batch, num_terms * dim]
    
    # Reshape to [batch, num_terms, dim]
    num_terms = params.mask['log_alpha'].shape[0]
    coeffs = raw_coeffs.reshape(batch_size, num_terms, output_dim)
    
    # Sample mask
    mask_obj = SparsityMask(num_terms)
    
    # Use same mask for all batch elements (shared sparsity structure)
    mask = mask_obj.sample(params.mask, mask_key, hard=hard_mask)  # [num_terms]
    
    # Apply mask
    masked_coeffs = coeffs * mask[None, :, None]  # [batch, num_terms, dim]
    
    return masked_coeffs, mask


def hypersindy_forward(
    params: HyperSINDyParams,
    x: Array,
    t: Optional[Array],
    dictionary: Dictionary,
    key: PRNGKey,
    output_dim: int,
    hard_mask: bool = False,
) -> Array:
    """Full forward pass: x → predicted drift.
    
    This generates a sample from the drift distribution.
    
    Args:
        params: HyperSINDy parameters.
        x: State, shape [batch, dim].
        t: Time, shape [batch] or None.
        dictionary: Observable dictionary.
        key: Random key.
        output_dim: State dimension.
        hard_mask: Whether to use hard mask.
        
    Returns:
        Predicted drift, shape [batch, dim].
    """
    x = jnp.atleast_2d(x)
    batch_size = x.shape[0]
    
    k1, k2 = jax.random.split(key)
    
    # Evaluate dictionary
    if t is not None:
        t = jnp.atleast_1d(t)
        if t.shape[0] == 1:
            t = jnp.broadcast_to(t, (batch_size,))
        theta = dictionary(x, t)  # [batch, num_terms]
    else:
        theta = dictionary(x)
    
    # For forward pass without encoder, use prior
    latent_dim = params.prior['mu'].shape[0]
    z = jax.random.normal(k1, (batch_size, latent_dim))
    
    # Decode to coefficients
    coeffs, mask = hypersindy_decode(params, z, k2, output_dim, hard_mask)
    
    # Compute drift: b(x) = Θ(x) @ ξ
    # [batch, num_terms] @ [batch, num_terms, dim] -> [batch, dim]
    drift = jnp.einsum('bn,bnd->bd', theta, coeffs)
    
    return drift


# =============================================================================
# Loss Functions
# =============================================================================

def hypersindy_loss(
    params: HyperSINDyParams,
    x: Array,
    dx_dt: Array,
    t: Optional[Array],
    dictionary: Dictionary,
    key: PRNGKey,
    config: HyperSINDyConfig,
) -> Tuple[Scalar, Dict[str, Scalar]]:
    """Compute HyperSINDy ELBO loss.
    
    ELBO = E_q[log p(dx/dt | z, x)] - KL(q(z|x,dx/dt) || p(z)) - λ L0(mask)
    
    Args:
        params: HyperSINDy parameters.
        x: States, shape [batch, dim].
        dx_dt: Time derivatives, shape [batch, dim].
        t: Times, shape [batch] or None.
        dictionary: Observable dictionary.
        key: Random key.
        config: Configuration.
        
    Returns:
        (loss, metrics_dict)
    """
    x = jnp.atleast_2d(x)
    dx_dt = jnp.atleast_2d(dx_dt)
    batch_size, dim = x.shape
    
    k1, k2 = jax.random.split(key)
    
    # === Encode ===
    mu_z, log_sigma_z = hypersindy_encode(params, x, dx_dt, t, config)
    
    # === Sample z ===
    z = hypersindy_sample_z(mu_z, log_sigma_z, k1)
    
    # === Decode to coefficients ===
    coeffs, mask = hypersindy_decode(params, z, k2, dim, hard_mask=False)
    
    # === Evaluate dictionary ===
    if t is not None:
        t = jnp.atleast_1d(t)
        if t.shape[0] == 1:
            t = jnp.broadcast_to(t, (batch_size,))
        theta = dictionary(x, t)
    else:
        theta = dictionary(x)
    
    # === Predict drift ===
    dx_dt_pred = jnp.einsum('bn,bnd->bd', theta, coeffs)
    
    # === Reconstruction loss (MSE) ===
    recon_loss = jnp.mean((dx_dt - dx_dt_pred) ** 2)
    
    # === KL divergence ===
    # KL(q(z|x) || p(z)) where p(z) = N(0, I)
    kl_loss = 0.5 * jnp.mean(
        jnp.sum(
            jnp.exp(2 * log_sigma_z) + mu_z ** 2 - 1 - 2 * log_sigma_z,
            axis=-1
        )
    )
    
    # === L0 sparsity penalty ===
    mask_obj = SparsityMask(dictionary.size, config.sparsity_temperature)
    l0_loss = mask_obj.l0_penalty(params.mask)
    
    # === Total loss ===
    loss = recon_loss + config.kl_weight * kl_loss + config.sparsity_lambda * l0_loss
    
    metrics = {
        'loss': loss,
        'recon_loss': recon_loss,
        'kl_loss': kl_loss,
        'l0_loss': l0_loss,
        'num_active_terms': jnp.sum(mask > 0.5),
    }
    
    return loss, metrics


# =============================================================================
# Training
# =============================================================================

def train_hypersindy(
    trajectories: Array,
    dictionary: Dictionary,
    config: HyperSINDyConfig,
    key: PRNGKey,
    num_iterations: int = 5000,
    batch_size: int = 256,
    verbose: int = 1,
) -> Tuple[HyperSINDyParams, Dict]:
    """Train HyperSINDy model.
    
    Args:
        trajectories: Trajectory data, shape [num_traj, time, dim].
        dictionary: Observable dictionary.
        config: HyperSINDy configuration.
        key: Random key.
        num_iterations: Number of training iterations.
        batch_size: Batch size.
        verbose: Verbosity level.
        
    Returns:
        (trained_params, training_info)
    """
    num_traj, num_times, dim = trajectories.shape
    dt = 1.0 / (num_times - 1)
    
    k1, k2 = jax.random.split(key)
    
    # Initialize parameters
    params = init_hypersindy(k1, dictionary, dim, config)
    
    # Prepare data: extract (x, dx/dt, t) tuples
    X_all = []
    dX_dt_all = []
    T_all = []
    
    times = jnp.linspace(0, 1, num_times)
    
    for traj_idx in range(num_traj):
        for t_idx in range(num_times - 1):
            X_all.append(trajectories[traj_idx, t_idx])
            dX_dt_all.append(
                (trajectories[traj_idx, t_idx + 1] - trajectories[traj_idx, t_idx]) / dt
            )
            T_all.append(times[t_idx])
    
    X_all = jnp.stack(X_all)
    dX_dt_all = jnp.stack(dX_dt_all)
    T_all = jnp.stack(T_all)
    
    num_samples = len(X_all)
    
    # Initialize optimizer (Adam)
    def init_adam(p):
        return {
            'm': jax.tree_util.tree_map(jnp.zeros_like, p),
            'v': jax.tree_util.tree_map(jnp.zeros_like, p),
            'step': 0,
        }
    
    opt_state = init_adam(params)
    
    def adam_update(opt, grads, params, lr=1e-3):
        beta1, beta2, eps = 0.9, 0.999, 1e-8
        step = opt['step'] + 1
        
        m = jax.tree_util.tree_map(
            lambda m, g: beta1 * m + (1 - beta1) * g, opt['m'], grads
        )
        v = jax.tree_util.tree_map(
            lambda v, g: beta2 * v + (1 - beta2) * g**2, opt['v'], grads
        )
        
        m_hat = jax.tree_util.tree_map(lambda m: m / (1 - beta1**step), m)
        v_hat = jax.tree_util.tree_map(lambda v: v / (1 - beta2**step), v)
        
        new_params = jax.tree_util.tree_map(
            lambda p, m, v: p - lr * m / (jnp.sqrt(v) + eps),
            params, m_hat, v_hat
        )
        
        return new_params, {'m': m, 'v': v, 'step': step}
    
    # Training loop
    loss_history = []
    
    for step in range(num_iterations):
        k2, batch_key, loss_key = jax.random.split(k2, 3)
        
        # Sample batch
        batch_idx = jax.random.choice(batch_key, num_samples, (batch_size,), replace=False)
        x_batch = X_all[batch_idx]
        dx_batch = dX_dt_all[batch_idx]
        t_batch = T_all[batch_idx] if config.use_time_conditioning else None
        
        # Compute loss and gradients
        (loss, metrics), grads = jax.value_and_grad(
            lambda p: hypersindy_loss(p, x_batch, dx_batch, t_batch, dictionary, loss_key, config),
            has_aux=True
        )(params)
        
        # Update parameters
        params, opt_state = adam_update(opt_state, grads, params, config.learning_rate)
        
        loss_history.append(float(loss))
        
        if verbose >= 1 and step % 500 == 0:
            print(f"Step {step}: loss={loss:.4f}, recon={metrics['recon_loss']:.4f}, "
                  f"active_terms={int(metrics['num_active_terms'])}")
    
    # Get final active terms
    mask_obj = SparsityMask(dictionary.size, config.sparsity_temperature)
    active_indices = mask_obj.get_active_terms(params.mask)
    
    training_info = {
        'loss_history': jnp.array(loss_history),
        'final_loss': loss_history[-1],
        'active_terms': active_indices,
        'num_active_terms': len(active_indices),
        'config': config,
    }
    
    return params, training_info


# =============================================================================
# Drift Function Creation
# =============================================================================

def create_hypersindy_drift(
    params: HyperSINDyParams,
    dictionary: Dictionary,
    dim: int,
    reference_drift: Optional[Callable] = None,
    sigma: float = 1.0,
    use_mean: bool = True,
) -> Callable[[Array, Scalar], Array]:
    """Create drift function from trained HyperSINDy model.
    
    Args:
        params: Trained HyperSINDy parameters.
        dictionary: Observable dictionary.
        dim: State dimension.
        reference_drift: Optional reference drift to add.
        sigma: Diffusion coefficient (for SB drift).
        use_mean: If True, use mean coefficients instead of sampling.
        
    Returns:
        Drift function b(x, t) → [batch, dim].
    """
    def drift(x: Array, t: Scalar) -> Array:
        x = jnp.atleast_2d(x)
        batch_size = x.shape[0]
        
        if not hasattr(t, 'shape') or t.shape == ():
            t_arr = t * jnp.ones(batch_size)
        else:
            t_arr = t
        
        # Evaluate dictionary
        theta = dictionary(x, t_arr)  # [batch, num_terms]
        
        if use_mean:
            # Use mean of hypernetwork output (z = 0 for standard Gaussian prior)
            z = jnp.zeros((batch_size, params.prior['mu'].shape[0]))
            raw_coeffs = _mlp_forward(params.hypernetwork, z)
            num_terms = params.mask['log_alpha'].shape[0]
            coeffs = raw_coeffs.reshape(batch_size, num_terms, dim)
            
            # Apply hard mask
            mask = (jax.nn.sigmoid(params.mask['log_alpha']) > 0.5).astype(jnp.float32)
            coeffs = coeffs * mask[None, :, None]
        else:
            # This would require a key, so use mean for deterministic evaluation
            z = jnp.zeros((batch_size, params.prior['mu'].shape[0]))
            raw_coeffs = _mlp_forward(params.hypernetwork, z)
            num_terms = params.mask['log_alpha'].shape[0]
            coeffs = raw_coeffs.reshape(batch_size, num_terms, dim)
            mask = (jax.nn.sigmoid(params.mask['log_alpha']) > 0.5).astype(jnp.float32)
            coeffs = coeffs * mask[None, :, None]
        
        # Compute drift
        b_learned = jnp.einsum('bn,bnd->bd', theta, coeffs)
        
        # Add reference drift if provided
        if reference_drift is not None:
            b_ref = reference_drift(x, t)
            return b_ref + sigma**2 * b_learned
        
        return b_learned
    
    return drift


def get_sparse_equation(
    params: HyperSINDyParams,
    dictionary: Dictionary,
    dim: int,
    threshold: float = 0.5,
) -> Dict:
    """Extract sparse equation from trained model.
    
    Args:
        params: Trained parameters.
        dictionary: Dictionary used.
        dim: State dimension.
        threshold: Activation threshold.
        
    Returns:
        Dictionary with equation information.
    """
    # Get mask probabilities
    mask_probs = jax.nn.sigmoid(params.mask['log_alpha'])
    active_mask = mask_probs > threshold
    
    # Get mean coefficients
    latent_dim = params.prior['mu'].shape[0]
    z_mean = jnp.zeros((1, latent_dim))
    raw_coeffs = _mlp_forward(params.hypernetwork, z_mean)
    num_terms = len(mask_probs)
    coeffs = raw_coeffs.reshape(num_terms, dim)
    
    # Apply mask
    masked_coeffs = coeffs * active_mask[:, None]
    
    # Get term names if available
    term_names = None
    if hasattr(dictionary, 'get_term_names'):
        term_names = dictionary.get_term_names()
    
    active_indices = jnp.where(active_mask)[0]
    
    return {
        'coefficients': masked_coeffs,
        'active_indices': active_indices,
        'active_coeffs': masked_coeffs[active_mask],
        'mask_probabilities': mask_probs,
        'term_names': term_names,
        'num_active': int(jnp.sum(active_mask)),
    }


# =============================================================================
# Module Exports
# =============================================================================

__all__ = [
    'HyperSINDyConfig',
    'HyperSINDyParams',
    'SparsityMask',
    'init_hypersindy',
    'hypersindy_encode',
    'hypersindy_sample_z',
    'hypersindy_decode',
    'hypersindy_forward',
    'hypersindy_loss',
    'train_hypersindy',
    'create_hypersindy_drift',
    'get_sparse_equation',
]
